version: "3"
services:
  db:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: yoga123
      MONGODB_DATABASE: graphqlYoga
    volumes:
      - "./containers/mongo:/data/db"
  maana-q-lambda-server:
    image: "services.azurecr.io/maana-q-lambda-server:v1.1"
    ports:
      - "4000:4000"
    networks:
      - net
    environment:
      MONGODB_HOST: db:27017
networks:
  net:
