version: '3'
services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    networks:
      - net
    environment:
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: yoga123
      MONGODB_DATABASE: graphqlYoga
    volumes:
      - './containers/mongo:/data/db'
  helpers:
    image: 'maana-q-lambda-server'
    ports:
      - '4000:4000'
    networks:
      - net
    environment:
      MONGODB_HOST: db:27017
networks:
  net:
