apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: maana-q-lambda-server-db
  name: maana-q-lambda-server-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: maana-q-lambda-server-db
    spec:
      containers:
      - env:
        - name: MONGODB_DATABASE
          value: graphqlYoga
        - name: MONGODB_PASSWORD
          value: yoga123
        - name: MONGODB_USERNAME
          value: graphql
        image: bitnami/mongodb:latest
        name: maana-q-lambda-server-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/maana-q-lambda-server-db
          name: maana-q-lambda-server-db-claim0
      restartPolicy: Always
      volumes:
      - name: maana-q-lambda-server-db-claim0
        persistentVolumeClaim:
          claimName: maana-q-lambda-server-db-claim0
status: {}
